### DISCUSSION TITLE
Can't update Globaleaks in GitLab

### DISCUSSION THREAD

**Discussion by Herkatus** [globaleaks/globaleaks-whistleblowing-software#4400] [Q&A]
So, I was tasked to understand why Globaleaks is not being updated. My company uses GitLab and I'm fairly new to it and I can't understand what is failing because the pipeline works (or is not showing errors.

.gitlab-ci.yml
 ```
variables:

  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote

  
stages:
  - build
  - deploy

docker-build:
  image: docker:24.0.7-dind-alpine3.18
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" ./GlobaLeaks/docker
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no core@$DEPLOY_HOST /usr/bin/docker compose --project-directory /opt/globaleaks up -d --pull always --force-recreate`
```

.gitmodules
```
[submodule "GlobaLeaks"]
	path = GlobaLeaks
	url = https://github.com/globaleaks/globaleaks.git
	branch = stable
```
As I said the pipeline doesn't fail but I'm stuck on version 5.0.45
Any ideas?
