### DISCUSSION TITLE
Virtualmin and proxy reverse

### DISCUSSION THREAD

**Discussion by green999ke** [globaleaks/globaleaks-whistleblowing-software#4529] [Q&A]
Hi, I would like to ask for your help because I am having difficulty running three environments on three subdomains on the same server.

I decided to use docker for each individual environment on a debian machine with virtualmin installed.

First I created this docker file with all the services:
```yml
version: "3"
services:
  globaleaks-sirte:
    image: globaleaks/globaleaks:v5.0.71
    container_name: globaleaks-sirte
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - sirte:/var/globaleaks
    restart: unless-stopped

  globaleaks-mega:
    image: globaleaks/globaleaks:v5.0.71
    container_name: globaleaks-mega
    ports:
      - "8082:8080"
      - "8453:8443"
    volumes:
      - mega:/var/globaleaks
    restart: unless-stopped

  globaleaks-gv:
    image: globaleaks/globaleaks:v5.0.71
    container_name: globaleaks-gv
    ports:
      - "8083:8080"
      - "8463:8443"
    volumes:
      - gv:/var/globaleaks
    restart: unless-stopped

volumes:
  gv:
  mega:
  sirte:
```

after which I followed the initial part of this discussion (https://github.com/orgs/globaleaks/discussions/3789) to do the reverse proxy.

However, the service is still not reachable.
Would someone who has experienced the same issue please help me out?
